services:
  database:
    image: mariadb:latest # Use the last mariadb version on Docker Hub
    container_name: whatsappbro-database
    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: WhatsappBro
      MYSQL_USER: Admin
      MYSQL_PASSWORD: 123
    volumes:
      - whatsappbro_mariadb_data:/var/lib/mysql
      - ./server/src/db/schema.sql:/docker-entrypoint-initdb.d/schema.sql # Run the script "schema.sql" for first time to create all
    ports:
      - '3306:3306' # Default MariaDB port
    restart: always # Always restart when the service stop, becouse we allways need the DB

  server:
    container_name: whatsappbro-server
    build:
      context: .
      dockerfile: ./server/Dockerfile
    environment:
      NODE_ENV: development
      DB_HOST: database
      DB_USER: Admin
      DB_PASSWORD: 123
      DB_NAME: WhatsappBro
    ports:
      - '3000:3000'
    depends_on:
      - database

  client:
    container_name: whatsappbro-client
    build:
      context: .
      dockerfile: ./client/Dockerfile
    ports:
      - '5173:5173'
    depends_on:
      - server

# Volume to save all the MariaDB data in a persistently from
volumes:
  whatsappbro_mariadb_data:
